// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TuroApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Car
    {
        /// <summary>
        /// Initializes a new instance of the Car class.
        /// </summary>
        public Car() { }

        /// <summary>
        /// Initializes a new instance of the Car class.
        /// </summary>
        public Car(long? id = default(long?), string make = default(string), string model = default(string), int? year = default(int?), int? tripsTaken = default(int?), double? dailyPrice = default(double?), DateTime? createdTime = default(DateTime?), double? tripsPerMonth = default(double?))
        {
            Id = id;
            Make = make;
            Model = model;
            Year = year;
            TripsTaken = tripsTaken;
            DailyPrice = dailyPrice;
            CreatedTime = createdTime;
            TripsPerMonth = tripsPerMonth;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "make")]
        public string Make { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public string Model { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tripsTaken")]
        public int? TripsTaken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dailyPrice")]
        public double? DailyPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdTime")]
        public DateTime? CreatedTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tripsPerMonth")]
        public double? TripsPerMonth { get; private set; }

    }
}
