// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TuroApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CarStats
    {
        /// <summary>
        /// Initializes a new instance of the CarStats class.
        /// </summary>
        public CarStats() { }

        /// <summary>
        /// Initializes a new instance of the CarStats class.
        /// </summary>
        public CarStats(int? total = default(int?), IDictionary<string, int?> year = default(IDictionary<string, int?>), IDictionary<string, int?> make = default(IDictionary<string, int?>), IDictionary<string, int?> model = default(IDictionary<string, int?>))
        {
            Total = total;
            Year = year;
            Make = make;
            Model = model;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public int? Total { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "year")]
        public IDictionary<string, int?> Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "make")]
        public IDictionary<string, int?> Make { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public IDictionary<string, int?> Model { get; set; }

    }
}
