// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TuroApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EncoderFallback
    {
        /// <summary>
        /// Initializes a new instance of the EncoderFallback class.
        /// </summary>
        public EncoderFallback() { }

        /// <summary>
        /// Initializes a new instance of the EncoderFallback class.
        /// </summary>
        public EncoderFallback(bool? bIsMicrosoftBestFitFallback = default(bool?))
        {
            BIsMicrosoftBestFitFallback = bIsMicrosoftBestFitFallback;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bIsMicrosoftBestFitFallback")]
        public bool? BIsMicrosoftBestFitFallback { get; set; }

    }
}
