// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TuroApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Encoding
    {
        /// <summary>
        /// Initializes a new instance of the Encoding class.
        /// </summary>
        public Encoding() { }

        /// <summary>
        /// Initializes a new instance of the Encoding class.
        /// </summary>
        public Encoding(int? mCodePage = default(int?), CodePageDataItem dataItem = default(CodePageDataItem), bool? mIsReadOnly = default(bool?), EncoderFallback encoderFallback = default(EncoderFallback), DecoderFallback decoderFallback = default(DecoderFallback))
        {
            MCodePage = mCodePage;
            DataItem = dataItem;
            MIsReadOnly = mIsReadOnly;
            EncoderFallback = encoderFallback;
            DecoderFallback = decoderFallback;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_codePage")]
        public int? MCodePage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataItem")]
        public CodePageDataItem DataItem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_isReadOnly")]
        public bool? MIsReadOnly { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "encoderFallback")]
        public EncoderFallback EncoderFallback { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "decoderFallback")]
        public DecoderFallback DecoderFallback { get; set; }

    }
}
