// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TuroApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MediaTypeMapping
    {
        /// <summary>
        /// Initializes a new instance of the MediaTypeMapping class.
        /// </summary>
        public MediaTypeMapping() { }

        /// <summary>
        /// Initializes a new instance of the MediaTypeMapping class.
        /// </summary>
        public MediaTypeMapping(MediaTypeHeaderValue mediaType = default(MediaTypeHeaderValue))
        {
            MediaType = mediaType;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MediaType")]
        public MediaTypeHeaderValue MediaType { get; private set; }

    }
}
