// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TuroApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MediaTypeFormatter
    {
        /// <summary>
        /// Initializes a new instance of the MediaTypeFormatter class.
        /// </summary>
        public MediaTypeFormatter() { }

        /// <summary>
        /// Initializes a new instance of the MediaTypeFormatter class.
        /// </summary>
        public MediaTypeFormatter(IList<MediaTypeHeaderValue> supportedMediaTypes = default(IList<MediaTypeHeaderValue>), IList<Encoding> supportedEncodings = default(IList<Encoding>), IList<MediaTypeMapping> mediaTypeMappings = default(IList<MediaTypeMapping>), object requiredMemberSelector = default(object))
        {
            SupportedMediaTypes = supportedMediaTypes;
            SupportedEncodings = supportedEncodings;
            MediaTypeMappings = mediaTypeMappings;
            RequiredMemberSelector = requiredMemberSelector;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SupportedMediaTypes")]
        public IList<MediaTypeHeaderValue> SupportedMediaTypes { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SupportedEncodings")]
        public IList<Encoding> SupportedEncodings { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MediaTypeMappings")]
        public IList<MediaTypeMapping> MediaTypeMappings { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RequiredMemberSelector")]
        public object RequiredMemberSelector { get; set; }

    }
}
