// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TuroApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Query object
    /// </summary>
    public partial class Query
    {
        /// <summary>
        /// Initializes a new instance of the Query class.
        /// </summary>
        public Query() { }

        /// <summary>
        /// Initializes a new instance of the Query class.
        /// </summary>
        public Query(string location, string make = default(string), string model = default(string))
        {
            Location = location;
            Make = make;
            Model = model;
        }

        /// <summary>
        /// SoFL= 26.16,-80.20
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string Location { get; set; }

        /// <summary>
        /// Car make
        /// </summary>
        [JsonProperty(PropertyName = "make")]
        public string Make { get; set; }

        /// <summary>
        /// Car model
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public string Model { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Location == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Location");
            }
        }
    }
}
