// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Offleaseonly;
using Offleaseonly.Models;

namespace Offleaseonly
{
    public static partial class CarOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the Offleaseonly.ICarOperations.
        /// </param>
        /// <param name='vin'>
        /// Required.
        /// </param>
        public static Car Get(this ICarOperations operations, string vin)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICarOperations)s).GetAsync(vin);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Offleaseonly.ICarOperations.
        /// </param>
        /// <param name='vin'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Car> GetAsync(this ICarOperations operations, string vin, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<Offleaseonly.Models.Car> result = await operations.GetWithOperationResponseAsync(vin, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
