// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Offleaseonly;
using Offleaseonly.Models;

namespace Offleaseonly
{
    public static partial class CarsExtensions
    {
        /// <param name='operations'>
        /// Reference to the Offleaseonly.ICars.
        /// </param>
        /// <param name='take'>
        /// Required.
        /// </param>
        /// <param name='skip'>
        /// Required.
        /// </param>
        /// <param name='query'>
        /// Required.
        /// </param>
        public static IList<Car> Get(this ICars operations, int take, int skip, string query)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ICars)s).GetAsync(take, skip, query);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Offleaseonly.ICars.
        /// </param>
        /// <param name='take'>
        /// Required.
        /// </param>
        /// <param name='skip'>
        /// Required.
        /// </param>
        /// <param name='query'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Car>> GetAsync(this ICars operations, int take, int skip, string query, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<Offleaseonly.Models.Car>> result = await operations.GetWithOperationResponseAsync(take, skip, query, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
