// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Offleaseonly.Models;

namespace Offleaseonly
{
    public partial interface ICars
    {
        /// <param name='take'>
        /// Required.
        /// </param>
        /// <param name='skip'>
        /// Required.
        /// </param>
        /// <param name='query'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<Car>>> GetWithOperationResponseAsync(int take, int skip, string query, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
