// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Microsoft.Rest;
using Offleaseonly;

namespace Offleaseonly
{
    public partial interface IOffleaseonlyClient : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri
        {
            get; set; 
        }
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        ServiceClientCredentials Credentials
        {
            get; set; 
        }
        
        ICarOperations Car
        {
            get; 
        }
        
        ICars Cars
        {
            get; 
        }
        
        IScrape Scrape
        {
            get; 
        }
        
        IStats Stats
        {
            get; 
        }
    }
}
