// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TuroApi
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for Stats.
    /// </summary>
    public static partial class StatsExtensions
    {
            /// <summary>
            /// Get car statistics in a given location
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='qlocation'>
            /// SoFL= 26.16,-80.20
            /// </param>
            /// <param name='qmake'>
            /// Car make
            /// </param>
            /// <param name='qmodel'>
            /// Car model
            /// </param>
            public static CarStats Get(this IStats operations, string qlocation, string qmake = default(string), string qmodel = default(string))
            {
                return Task.Factory.StartNew(s => ((IStats)s).GetAsync(qlocation, qmake, qmodel), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get car statistics in a given location
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='qlocation'>
            /// SoFL= 26.16,-80.20
            /// </param>
            /// <param name='qmake'>
            /// Car make
            /// </param>
            /// <param name='qmodel'>
            /// Car model
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CarStats> GetAsync(this IStats operations, string qlocation, string qmake = default(string), string qmodel = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(qlocation, qmake, qmodel, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
