// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Offleaseonly.Models
{
    public partial class Car
    {
        private int? _cleanCarFax;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? CleanCarFax
        {
            get { return this._cleanCarFax; }
            set { this._cleanCarFax = value; }
        }
        
        private string _color;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Color
        {
            get { return this._color; }
            set { this._color = value; }
        }
        
        private string _eng;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Eng
        {
            get { return this._eng; }
            set { this._eng = value; }
        }
        
        private string _image;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Image
        {
            get { return this._image; }
            set { this._image = value; }
        }
        
        private string _link;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Link
        {
            get { return this._link; }
            set { this._link = value; }
        }
        
        private string _location;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Location
        {
            get { return this._location; }
            set { this._location = value; }
        }
        
        private string _make;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Make
        {
            get { return this._make; }
            set { this._make = value; }
        }
        
        private int? _mileage;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Mileage
        {
            get { return this._mileage; }
            set { this._mileage = value; }
        }
        
        private string _model;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Model
        {
            get { return this._model; }
            set { this._model = value; }
        }
        
        private int? _price;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Price
        {
            get { return this._price; }
            set { this._price = value; }
        }
        
        private string _stock;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Stock
        {
            get { return this._stock; }
            set { this._stock = value; }
        }
        
        private string _trans;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Trans
        {
            get { return this._trans; }
            set { this._trans = value; }
        }
        
        private string _vin;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Vin
        {
            get { return this._vin; }
            set { this._vin = value; }
        }
        
        private int? _year;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Year
        {
            get { return this._year; }
            set { this._year = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Car class.
        /// </summary>
        public Car()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken cleanCarFaxValue = inputObject["cleanCarFax"];
                if (cleanCarFaxValue != null && cleanCarFaxValue.Type != JTokenType.Null)
                {
                    this.CleanCarFax = ((int)cleanCarFaxValue);
                }
                JToken colorValue = inputObject["color"];
                if (colorValue != null && colorValue.Type != JTokenType.Null)
                {
                    this.Color = ((string)colorValue);
                }
                JToken engValue = inputObject["eng"];
                if (engValue != null && engValue.Type != JTokenType.Null)
                {
                    this.Eng = ((string)engValue);
                }
                JToken imageValue = inputObject["image"];
                if (imageValue != null && imageValue.Type != JTokenType.Null)
                {
                    this.Image = ((string)imageValue);
                }
                JToken linkValue = inputObject["link"];
                if (linkValue != null && linkValue.Type != JTokenType.Null)
                {
                    this.Link = ((string)linkValue);
                }
                JToken locationValue = inputObject["location"];
                if (locationValue != null && locationValue.Type != JTokenType.Null)
                {
                    this.Location = ((string)locationValue);
                }
                JToken makeValue = inputObject["make"];
                if (makeValue != null && makeValue.Type != JTokenType.Null)
                {
                    this.Make = ((string)makeValue);
                }
                JToken mileageValue = inputObject["mileage"];
                if (mileageValue != null && mileageValue.Type != JTokenType.Null)
                {
                    this.Mileage = ((int)mileageValue);
                }
                JToken modelValue = inputObject["model"];
                if (modelValue != null && modelValue.Type != JTokenType.Null)
                {
                    this.Model = ((string)modelValue);
                }
                JToken priceValue = inputObject["price"];
                if (priceValue != null && priceValue.Type != JTokenType.Null)
                {
                    this.Price = ((int)priceValue);
                }
                JToken stockValue = inputObject["stock"];
                if (stockValue != null && stockValue.Type != JTokenType.Null)
                {
                    this.Stock = ((string)stockValue);
                }
                JToken transValue = inputObject["trans"];
                if (transValue != null && transValue.Type != JTokenType.Null)
                {
                    this.Trans = ((string)transValue);
                }
                JToken vinValue = inputObject["vin"];
                if (vinValue != null && vinValue.Type != JTokenType.Null)
                {
                    this.Vin = ((string)vinValue);
                }
                JToken yearValue = inputObject["year"];
                if (yearValue != null && yearValue.Type != JTokenType.Null)
                {
                    this.Year = ((int)yearValue);
                }
            }
        }
    }
}
