// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using Offleaseonly.Models;

namespace Offleaseonly.Models
{
    public static partial class CarCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Car> DeserializeJson(JToken inputObject)
        {
            IList<Car> deserializedObject = new List<Car>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Car car = new Car();
                car.DeserializeJson(iListValue);
                deserializedObject.Add(car);
            }
            return deserializedObject;
        }
    }
}
