// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OffleaseOnly.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Car
    {
        /// <summary>
        /// Initializes a new instance of the Car class.
        /// </summary>
        public Car() { }

        /// <summary>
        /// Initializes a new instance of the Car class.
        /// </summary>
        public Car(string vin = default(string), string eng = default(string), string make = default(string), string model = default(string), string color = default(string), string trans = default(string), string stock = default(string), string image = default(string), string link = default(string), string location = default(string), int? cleanCarFax = default(int?), int? mileage = default(int?), int? price = default(int?), int? year = default(int?))
        {
            Vin = vin;
            Eng = eng;
            Make = make;
            Model = model;
            Color = color;
            Trans = trans;
            Stock = stock;
            Image = image;
            Link = link;
            Location = location;
            CleanCarFax = cleanCarFax;
            Mileage = mileage;
            Price = price;
            Year = year;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vin")]
        public string Vin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eng")]
        public string Eng { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "make")]
        public string Make { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public string Model { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "color")]
        public string Color { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trans")]
        public string Trans { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stock")]
        public string Stock { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image")]
        public string Image { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "link")]
        public string Link { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cleanCarFax")]
        public int? CleanCarFax { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mileage")]
        public int? Mileage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public int? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "year")]
        public int? Year { get; set; }

    }
}
