// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OffleaseOnly.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CarStats
    {
        /// <summary>
        /// Initializes a new instance of the CarStats class.
        /// </summary>
        public CarStats() { }

        /// <summary>
        /// Initializes a new instance of the CarStats class.
        /// </summary>
        public CarStats(IDictionary<string, int?> cleanCarFax = default(IDictionary<string, int?>), IDictionary<string, int?> year = default(IDictionary<string, int?>), IDictionary<string, int?> eng = default(IDictionary<string, int?>), IDictionary<string, int?> make = default(IDictionary<string, int?>), IDictionary<string, int?> location = default(IDictionary<string, int?>))
        {
            CleanCarFax = cleanCarFax;
            Year = year;
            Eng = eng;
            Make = make;
            Location = location;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cleanCarFax")]
        public IDictionary<string, int?> CleanCarFax { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "year")]
        public IDictionary<string, int?> Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eng")]
        public IDictionary<string, int?> Eng { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "make")]
        public IDictionary<string, int?> Make { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public IDictionary<string, int?> Location { get; set; }

    }
}
