// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OffleaseOnly.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Price
    {
        /// <summary>
        /// Initializes a new instance of the Price class.
        /// </summary>
        public Price() { }

        /// <summary>
        /// Initializes a new instance of the Price class.
        /// </summary>
        public Price(int? priceProperty = default(int?), DateTime? date = default(DateTime?))
        {
            PriceProperty = priceProperty;
            Date = date;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public int? PriceProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public DateTime? Date { get; set; }

    }
}
